---
title: "Class09"
author: "Khoi Tran"
date: "April 30, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Exploratory Data Analysis
```{r}
wisc.df<-read.csv("WisconsinCancer.csv")
wisc.df
```

```{r}
fna.data<- "data/WisconsinCancer.csv"
wisc.data<- as.matrix(wisc.df[,3:32])
row.names(wisc.data) <- wisc.df$id
diagnosis <- as.numeric(wisc.df$diagnosis == "M")

```

```{r}
#notes 3:32
```

```{r}
#Questions
#Q1. How many observations are in this dataset?
nrow(wisc.data)
#Q2. How many variables/features in the data are suffixed with _mean?
columnnames <- colnames(wisc.data)
length(grep("_mean",columnnames))
#Q3. How many of the observations have a malignant diagnosis?
table(diagnosis)
```

#Principal Conponent Analysis
```{r}
colMeans(wisc.data)
apply(wisc.data,2,sd)
wisc.pr <- prcomp(wisc.data,scale = TRUE)
summary(wisc.pr)
```
```{r}
#Biplot
biplot(wisc.pr)
#PC1 vs PC2 Plot
plot(wisc.pr$x[,1:2],col = (diagnosis + 1),  xlab = "PC1", ylab = "PC2")
#PC1 vs PC3 Plot
plot(wisc.pr$x[,1:3],col = (diagnosis + 1),  xlab = "PC1", ylab = "PC3")
```
```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```

```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
```

```{r}
wisc.hclust <- hclust(data.dist)
plot(wisc.hclust) 
abline(h=19, col="red", lty=2)
```
```{r}
wisc.hclust.cluster <-cutree(wisc.hclust,k=2, h=19)
table(wisc.hclust.cluster,diagnosis)
```

```{r}
grps <- cutree(wisc.hclust, k=2)
table (grps)
table (grps, diagnosis)
```
```{r}
plot(wisc.pr$x[,1:2], col=grps)
plot(wisc.pr$x[,1:2], col=diagnosis+1)
library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=diagnosis+1)
rglwidget(width = 400, height = 400)
```

```{r}
new <- read.csv("https://tinyurl.com/new-samples-CSV")
npc <- predict(wisc.pr,newdata = new)
npc
plot(wisc.pr$x[,1:2], col=grps)
points(npc[,1],npc[,2], col = "blue",pch =16)
```




