---
title: "Class08"
author: "Khoi Tran"
date: "April 25, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# K-means clustering

```

```{r}
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
km<-kmeans(x,2,20)
km

```

```{r}
km$size
km$cluster
km$centers
```

```{r}
plot(x,col=km$cluster)
points(km$centers, pch=18, col="green", cex = 3)
```
```{r}
#Hierarchical Clustering
Distance <- dist(x)
HCluster <- hclust(Distance)
plot(HCluster)
cutree(HCluster, k=2)
```


```{r}
plot(HCluster, h=6)
cutree(HCluster, h=2)
```

```{r}
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
plot(x)
col<- as.factor(rep(c("c1","C2","c3")))
plot(x, col=col)

```
```{r}
#PCA Principal Component Analysis
## You can also download this file from the class website!
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1) 
colnames(mydata)
```

```{r}
pca<-prcomp(t(mydata))
plot(pca$x[,1],pca$x[,2],ylab = "hi")
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```
```{r}
colvec <- colnames(mydata)
colvec[grep("wt", colvec)] <- "red"
colvec[grep("ko", colvec)] <- "blue"
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```
```{r}
#Inclass
x <- read.csv("UK_foods.csv", row.names=1)
pca <- prcomp (t(x))
barplot(as.matrix(x),horiz = FALSE, beside=T, col=rainbow(nrow(x)))
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
text(pca$x[,1], pca$x[,2], colnames(x))
par(mar=c(10, 3, 0.35, 0))
barplot( pca$rotation[,1], las=2 )

```


