---
title: 'Class 6: R Functions'
author: "Khoi Tran"
date: "April 18, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is some text

```{r}
read.table("Class06_files/test1.txt", header = TRUE, sep = ",")
```
```{r}
read.table("Class06_files/test2.txt", header = TRUE, sep = "$")
```
```{r}
read.table("Class06_files/test3.txt", header = FALSE)
```

#Function
```{r}
add <- function(x,y=1){
  #the body
  x+y
}
```
```{r}
add(9)
```
```{r}
add(10,10
    )
```
```{r}
add(c(1,2,4),8)
```
```{r}
#add(1,"word") Results in Error
#add(1,1,1) Results in error

```

```{r}
rescale <- function(x) {
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale(c(1:10))
```
```{r}
rescale(c(1,2,3,NA,4))

```
```{r}
rescale.na.rm.false <- function(x) {
 rng <-range(x, na.rm = FALSE)
 (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("Never stop singing")
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3(c(1,3,NA,10))
```

```{r}
rescale3(c(1,3,NA,10), plot=TRUE)

```

```{r}
#rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
#  if(!numeric())
 #rng <-range(x, na.rm=na.rm)
 #print("Hello")
 #answer <- (x - rng[1]) / (rng[2] - rng[1])
 #print("is it me you are looking for?")
 #if(plot) {
 #plot(answer, typ="b", lwd=4)
 #}
 #print("Never stop singing")
 #print("I can see it in ...")
 #return(answer)
```

